name: CI Pipeline
on:
  push:
    branches:[ "main" ]
    pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubunto-latest

    steps:
    - name: Checkout repository
      uses: actions/chaeckout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Run tests
      run: python -m unittest discover -s . -p "test_.py"
